import Card from "../ui/Card";
import Pill from "../ui/Pill";
import { toneSoftBg, type Tone } from "../ui/tone";

const insights: Array<{ title: string; description: string; icon: string; tone: Tone }> = [
  {
    title: "Opportunity of the Day",
    description:
      "Kitchen gadgets continue to outperform most categories with strong engagement and high conversion rates.",
    icon: "🚀",
    tone: "positive",
  },
  {
    title: "Market Warning",
    description:
      "Phone accessories are becoming more competitive. Focus on unique products instead of saturated items.",
    icon: "⚠️",
    tone: "warning",
  },
  {
    title: "Best Country Today",
    description:
      "United States shows the highest purchase intent for home improvement and lifestyle products.",
    icon: "🌎",
    tone: "data",
  },
  {
    title: "Viral Category",
    description:
      "Portable lifestyle products continue to trend strongly across TikTok and Instagram Reels.",
    icon: "🔥",
    tone: "ai",
  },
  {
    title: "AI Recommendation",
    description:
      "Launch products with an AI Score above 90 and medium competition to maximize your success probability.",
    icon: "🤖",
    tone: "ai",
  },
];

export default function AIInsights() {
  return (
    <Card padding="none">
      <div className="flex items-center justify-between gap-3 border-b border-[var(--border-subtle)] p-6">
        <div>
          <h2 className="text-lg font-bold text-[var(--ink-900)]">AI Daily Brief</h2>
          <p className="mt-1 text-sm text-[var(--ink-500)]">Personalized insights generated by TrendPilot AI.</p>
        </div>
        <Pill tone="neutral">Updated today</Pill>
      </div>

      <div className="divide-y divide-[var(--border-subtle)]">
        {insights.map((item) => (
          <div key={item.title} className="flex gap-4 p-6">
            <span
              className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl text-lg ${toneSoftBg[item.tone]}`}
            >
              {item.icon}
            </span>

            <div className="min-w-0">
              <h3 className="font-semibold text-[var(--ink-900)]">{item.title}</h3>
              <p className="mt-1 text-sm leading-6 text-[var(--ink-500)]">{item.description}</p>
            </div>
          </div>
        ))}
      </div>
    </Card>
  );
}
