export default function AIInsights() {
  const insights = [
    {
      title: "Opportunity of the Day",
      description:
        "Kitchen gadgets continue to outperform most categories with strong engagement and high conversion rates.",
      icon: "🚀",
      color: "from-green-500 to-emerald-500",
    },
    {
      title: "Market Warning",
      description:
        "Phone accessories are becoming more competitive. Focus on unique products instead of saturated items.",
      icon: "⚠️",
      color: "from-orange-500 to-red-500",
    },
    {
      title: "Best Country Today",
      description:
        "United States shows the highest purchase intent for home improvement and lifestyle products.",
      icon: "🌎",
      color: "from-blue-500 to-cyan-500",
    },
    {
      title: "Viral Category",
      description:
        "Portable lifestyle products continue to trend strongly across TikTok and Instagram Reels.",
      icon: "🔥",
      color: "from-pink-500 to-purple-500",
    },
    {
      title: "AI Recommendation",
      description:
        "Launch products with an AI Score above 90 and medium competition to maximize your success probability.",
      icon: "🤖",
      color: "from-violet-500 to-indigo-500",
    },
  ];

  return (
    <section className="mt-10">

      <div className="flex items-center justify-between mb-6">

        <div>

          <h2 className="text-3xl font-bold">
            🤖 AI Daily Brief
          </h2>

          <p className="text-gray-500 mt-2">
            Personalized insights generated by TrendPilot AI.
          </p>

        </div>

        <span className="rounded-full bg-purple-100 px-4 py-2 text-sm font-semibold text-purple-700">
          Updated Today
        </span>

      </div>

      <div className="grid gap-6 lg:grid-cols-2">

        {insights.map((item) => (

          <div
            key={item.title}
            className="relative overflow-hidden rounded-3xl border border-gray-100 bg-white p-7 shadow-lg transition-all duration-300 hover:-translate-y-1 hover:shadow-2xl"
          >

            <div
              className={`absolute right-0 top-0 h-24 w-24 rounded-bl-full bg-gradient-to-br ${item.color} opacity-10`}
            />

            <div className="relative z-10 flex gap-5">

              <div
                className={`flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-r ${item.color} text-3xl shadow-lg`}
              >
                {item.icon}
              </div>

              <div>

                <h3 className="text-xl font-bold text-gray-900">
                  {item.title}
                </h3>

                <p className="mt-3 leading-7 text-gray-600">
                  {item.description}
                </p>

              </div>

            </div>

          </div>

        ))}

      </div>

    </section>
  );
}