import { 
    ProductReport, 
    LaunchStatus, 
    RiskLevel, 
    CompetitionLevel, 
    AdvertisingPlatform 
  } from "../types/report";
  import { Product } from "../types/product";
  
  /**
   * Interface representing the existing core ProductScore calculation engine contract.
   */
  export interface ProductScore {
    winningProbability: number;
    aiScore: number;
    trendScore: number;
    launchStatus: LaunchStatus;
    riskLevel: RiskLevel;
  }
  
  /**
   * Normalizes input numbers into valid bounding ranges (0 - 100).
   */
  function clamp(value: number, min: number = 0, max: number = 100): number {
    if (isNaN(value)) return min;
    return Math.min(Math.max(value, min), max);
  }
  
  /**
   * Standardizes raw competition input to strongly typed entity.
   */
  function normalizeCompetition(competition?: string): CompetitionLevel {
    const val = (competition || "").toLowerCase();
    if (val === "low") return "Low";
    if (val === "high") return "High";
    return "Medium";
  }
  
  /**
   * Normalizes advertising platform input into strongly typed AdvertisingPlatform objects.
   */
  function normalizeAdvertisingPlatforms(
    platforms?: (string | Partial<AdvertisingPlatform>)[]
  ): AdvertisingPlatform[] {
    if (!platforms || platforms.length === 0) {
      return [
        {
          name: "TikTok Ads",
          score: 90,
          reason: "High viral potential and strong engagement for impulse-buy products."
        },
        {
          name: "Meta Ads",
          score: 85,
          reason: "Proven targeting options for high-intent e-commerce shoppers."
        }
      ];
    }
  
    return platforms.map((platform) => {
      if (typeof platform === "string") {
        return {
          name: platform,
          score: 80,
          reason: `Recommended channel for scaling ${platform} campaigns.`
        };
      }
      return {
        name: platform.name || "Paid Social",
        score: clamp(platform.score ?? 80),
        reason: platform.reason || "High conversion potential based on audience match."
      };
    });
  }
  
  /**
   * Transforms a Product entity, its pre-calculated ProductScore, and AI insights 
   * into a single unified ProductReport object.
   * 
   * Does NOT recalculate business scores; consumes ProductScore directly as truth.
   *
   * @param product Raw product entity from DB or search APIs
   * @param score Existing pre-computed ProductScore engine output
   * @param aiInsight Optional deep analysis generated by LLM engines
   * @returns Immutable ProductReport domain object
   */
  export function generateProductReport(
    product: Partial<Product> & { id: string | number },
    score: ProductScore,
    aiInsight?: Partial<ProductReport>
  ): ProductReport {
    const productId = String(product.id);
    
    // Dynamic currency extraction with USD fallback
    const currency = product.currency || "USD";
  
    // Financial metrics calculation
    const buyPrice = Number(product.buy_price) || 0;
    const sellingPrice = Number(product.selling_price) || 0;
    const profitMarginAmount = Number(product.profit) || Math.max(0, sellingPrice - buyPrice);
    const profitMarginPercentage = sellingPrice > 0 
      ? Math.round((profitMarginAmount / sellingPrice) * 100) 
      : 0;
    
    const estimatedRoas = buyPrice > 0 
      ? Number((sellingPrice / buyPrice).toFixed(2)) 
      : 1.0;
  
    // Consume scores directly from the ProductScore engine (No score math recalculation)
    const winningProbability = clamp(score.winningProbability);
    const aiScore = clamp(score.aiScore);
    const trendScore = clamp(score.trendScore);
    const recommendation = score.launchStatus;
    const risk = score.riskLevel;
  
    const competitionLevel = normalizeCompetition(product.competition);
  
    // Advertising platforms normalization
    const recommendedPlatforms = normalizeAdvertisingPlatforms(
      aiInsight?.advertisingPlatforms || aiInsight?.marketingAnalysis?.recommendedPlatforms
    );
  
    // Marketing & AI analysis integration
    const primaryHook = aiInsight?.marketingHook || 
      aiInsight?.marketingAnalysis?.primaryHook || 
      `High-converting ${product.category || "e-commerce"} solution with strong profit margin potential.`;
  
    const targetAudience = aiInsight?.targetAudience || 
      aiInsight?.marketingAnalysis?.targetAudience || 
      ["E-commerce Shoppers", "Social Media Impulse Buyers"];
  
    return {
      productId,
      score: {
        winningProbability,
        aiScore,
        trendScore,
      },
      recommendation,
      confidence: clamp(aiInsight?.confidence ?? 85),
      risk,
      summary: product.ai_reason || aiInsight?.summary || `${product.name || product.title || "Product"} exhibits strong commercial viability with an estimated profit margin of ${currency} ${profitMarginAmount}.`,
      strengths: aiInsight?.strengths || [
        `Healthy profit margin of ${profitMarginPercentage}%`,
        `Strong market momentum with trend score of ${trendScore}%`,
        `Optimal pricing structure for paid media scaling`
      ],
      weaknesses: aiInsight?.weaknesses || [
        `Requires targeted ad creative testing`,
        `Competition level evaluated as ${competitionLevel}`
      ],
      marketAnalysis: {
        competitionLevel,
        marketVelocityScore: trendScore,
        trendDirection: trendScore >= 60 ? "Upward" : "Stable",
        targetCountry: product.country || "US",
        demandVolume: trendScore >= 75 ? "High" : "Moderate",
      },
      marketingAnalysis: {
        primaryHook,
        targetAudience,
        recommendedPlatforms,
        adAngles: aiInsight?.marketingAnalysis?.adAngles || [
          "Problem-Solving Highlight",
          "Before vs After Demonstration",
          "Limited Time Promotion"
        ],
      },
      profitAnalysis: {
        buyPrice,
        sellingPrice,
        profitMarginAmount,
        profitMarginPercentage,
        estimatedRoas,
        currency,
      },
      advertisingPlatforms: recommendedPlatforms,
      marketingHook: primaryHook,
      targetAudience,
      generatedAt: new Date().toISOString(),
    };
  }