export type DataTier = "real" | "estimate" | "ai" | "general";

const TIER_CONFIG: Record<DataTier, { label: string; classes: string }> = {
  real: {
    label: "Real Data",
    classes: "border-[var(--border-subtle)] bg-[var(--surface-muted)] text-[var(--ink-700)]",
  },
  estimate: {
    label: "Deterministic Estimate",
    classes: "border-[var(--accent-data)]/25 bg-[var(--accent-data-soft)] text-[var(--accent-data)]",
  },
  ai: {
    label: "AI-Generated",
    classes: "border-[var(--accent-ai)]/25 bg-[var(--accent-ai-soft)] text-[var(--accent-ai)]",
  },
  general: {
    label: "General Recommendation",
    classes: "border-[var(--border-subtle)] bg-[var(--surface-muted)] text-[var(--ink-500)]",
  },
};

type Props = {
  tier: DataTier;
  className?: string;
};

/**
 * The one visual marker for "where did this number/text come from" used
 * throughout the Report. Four tiers, fixed meaning, never mixed:
 *   real     -- straight from the DataForSEO/search response
 *   estimate -- computed client/server-side by a deterministic formula
 *               (decisionEngine.ts, marketAnalyzer.ts, roiCalculator.ts,
 *               businessCoach.ts) -- not from real market data
 *   ai       -- generated by the OpenAI call (lib/services/generateMarketing)
 *   general  -- a static, non-product-specific recommendation
 * Never used to relabel or reinterpret a value, only to disclose its origin.
 */
export default function DataTierBadge({ tier, className = "" }: Props) {
  const config = TIER_CONFIG[tier];

  return (
    <span
      className={`inline-flex items-center rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${config.classes} ${className}`}
    >
      {config.label}
    </span>
  );
}
