import { ProductReport, LaunchStatus, RiskLevel, CompetitionLevel } from "../types/report";
import { Product } from "../types/product";

/**
 * Normalizes input strings or numbers into valid bounding ranges.
 */
function clamp(value: number, min: number = 0, max: number = 100): number {
  if (isNaN(value)) return min;
  return Math.min(Math.max(value, min), max);
}

/**
 * Determines launch status based on calculated winning probability.
 */
function deriveLaunchStatus(score: number): LaunchStatus {
  if (score >= 75) return "Launch Now";
  if (score >= 50) return "Watch";
  return "Skip";
}

/**
 * Calculates risk level based on competition, margin, and trend score.
 */
function deriveRiskLevel(competition: string, margin: number, trendScore: number): RiskLevel {
  const normalizedComp = (competition || "").toLowerCase();
  
  if (normalizedComp === "high" || margin < 15 || trendScore < 40) {
    return "High";
  }
  if (normalizedComp === "medium" || margin < 30 || trendScore < 70) {
    return "Medium";
  }
  return "Low";
}

/**
 * Standardizes raw competition input to strong typed entity.
 */
function normalizeCompetition(competition?: string): CompetitionLevel {
  const val = (competition || "").toLowerCase();
  if (val === "low") return "Low";
  if (val === "high") return "High";
  return "Medium";
}

/**
 * Generates a unified, single-source-of-truth ProductReport object.
 * 
 * Combines input product parameters, deterministic financial calculations, 
 * and fallback AI insights into a strict, validated schema consumed by the UI.
 * 
 * @param product Raw product entity from DB or search APIs
 * @param aiInsight Optional deep analysis generated by LLM engines
 * @returns Fully computed ProductReport object
 */
export function generateProductReport(
  product: Partial<Product> & { id: string | number },
  aiInsight?: Partial<ProductReport>
): ProductReport {
  const productId = String(product.id);
  
  // Financial metrics derivation
  const buyPrice = Number(product.buy_price) || 0;
  const sellingPrice = Number(product.selling_price) || 0;
  const profitMarginAmount = Number(product.profit) || Math.max(0, sellingPrice - buyPrice);
  const profitMarginPercentage = sellingPrice > 0 
    ? Math.round((profitMarginAmount / sellingPrice) * 100) 
    : 0;
  
  const estimatedRoas = buyPrice > 0 
    ? Number((sellingPrice / buyPrice).toFixed(2)) 
    : 1.0;

  // Scores derivation
  const aiScore = clamp(Number(product.ai_score ?? aiInsight?.score?.aiScore ?? 70));
  const trendScore = clamp(Number(product.trend_score ?? aiInsight?.score?.trendScore ?? 65));
  
  // Winning probability weighted calculation: 60% AI Score + 40% Trend Score
  const winningProbability = clamp(
    Math.round(aiScore * 0.6 + trendScore * 0.4)
  );

  const competitionLevel = normalizeCompetition(product.competition);
  const risk = deriveRiskLevel(competitionLevel, profitMarginPercentage, trendScore);
  const recommendation = deriveLaunchStatus(winningProbability);

  // Marketing & AI analysis integration with safe defaults
  const primaryHook = aiInsight?.marketingHook || 
    aiInsight?.marketingAnalysis?.primaryHook || 
    `High-converting ${product.category || "e-commerce"} solution with strong profit margin potential.`;

  const targetAudience = aiInsight?.targetAudience || 
    aiInsight?.marketingAnalysis?.targetAudience || 
    ["E-commerce Shoppers", "Social Media Impulse Buyers"];

  const recommendedPlatforms = aiInsight?.advertisingPlatforms || 
    aiInsight?.marketingAnalysis?.recommendedPlatforms || 
    ["TikTok Ads", "Meta Ads"];

  return {
    productId,
    score: {
      winningProbability,
      aiScore,
      trendScore,
    },
    recommendation,
    confidence: clamp(aiInsight?.confidence ?? 85),
    risk,
    summary: product.ai_reason || aiInsight?.summary || `${product.name || product.title || "Product"} exhibits strong commercial viability with an estimated profit margin of $${profitMarginAmount}.`,
    strengths: aiInsight?.strengths || [
      `Healthy profit margin of ${profitMarginPercentage}%`,
      `Strong market momentum with trend score of ${trendScore}%`,
      `Optimal pricing structure for paid media scaling`
    ],
    weaknesses: aiInsight?.weaknesses || [
      `Requires targeted ad creative testing`,
      `Competition level evaluated as ${competitionLevel}`
    ],
    marketAnalysis: {
      competitionLevel,
      marketVelocityScore: trendScore,
      trendDirection: trendScore >= 60 ? "Upward" : "Stable",
      targetCountry: product.country || "US",
      demandVolume: trendScore >= 75 ? "High" : "Moderate",
    },
    marketingAnalysis: {
      primaryHook,
      targetAudience,
      recommendedPlatforms,
      adAngles: aiInsight?.marketingAnalysis?.adAngles || [
        "Problem-Solving Highlight",
        "Before vs After Demonstration",
        "Limited Time Promotion"
      ],
    },
    profitAnalysis: {
      buyPrice,
      sellingPrice,
      profitMarginAmount,
      profitMarginPercentage,
      estimatedRoas,
      currency: "USD",
    },
    advertisingPlatforms: recommendedPlatforms,
    marketingHook: primaryHook,
    targetAudience,
    generatedAt: new Date().toISOString(),
  };
}