import type { Product } from "../../types/Product";

export const dummyProducts: Product[] = [
  {
    id: "1",
    source: "Shopify",
    platform: "Shopify",
    name: "Portable Blender",
    description: "Portable USB Blender",
    image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800",
    category: "Kitchen",
    brand: "Generic",
    product_url: "https://shopify.com",
    supplier: "AliExpress",
    supplier_url: "https://aliexpress.com",
    currency: "USD",
    buy_price: 18,
    selling_price: 49,
    profit: 31,
    roi: 172,
    sales: 1280,
    orders: 1280,
    reviews: 450,
    country: "Global",
    ai_score: 96,
    trend_score: 94,
    viral_score: 92,
    opportunity_score: 95,
    decision: "Strong Buy",
    competition: "Medium",
  },

  {
    id: "2",
    source: "Amazon",
    platform: "Amazon",
    name: "Magnetic Phone Holder",
    description: "Universal Magnetic Phone Holder",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800",
    category: "Accessories",
    brand: "Generic",
    product_url: "https://amazon.com",
    supplier: "CJ Dropshipping",
    supplier_url: "https://cjdropshipping.com",
    currency: "USD",
    buy_price: 6,
    selling_price: 48,
    profit: 42,
    roi: 700,
    sales: 7600,
    orders: 7600,
    reviews: 1200,
    country: "Global",
    ai_score: 94,
    trend_score: 92,
    viral_score: 90,
    opportunity_score: 93,
    decision: "Strong Buy",
    competition: "High",
  },

  {
    id: "3",
    source: "Shopify",
    platform: "Shopify",
    name: "LED Backpack",
    description: "LED Smart Backpack",
    image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800",
    category: "Fashion",
    brand: "Generic",
    product_url: "https://tiktok.com",
    supplier: "Zendrop",
    supplier_url: "https://zendrop.com",
    currency: "USD",
    buy_price: 29,
    selling_price: 60,
    profit: 31,
    roi: 107,
    sales: 2200,
    orders: 2200,
    reviews: 380,
    country: "Global",
    ai_score: 91,
    trend_score: 90,
    viral_score: 88,
    opportunity_score: 89,
    decision: "Strong Buy",
    competition: "Medium",
  },
];