export const dummyProducts = [
    {
      name: "Portable Blender",
      image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800",
      platform: "Shopify",
      category: "Kitchen",
      supplier: "AliExpress",
      supplier_url: "https://aliexpress.com",
      product_url: "https://shopify.com",
      buy_price: 18,
      selling_price: 49,
      profit: 31,
      sales: 1280,
      ai_score: 96,
      trend_score: 94,
    },
  
    {
      name: "Magnetic Phone Holder",
      image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800",
      platform: "Amazon",
      category: "Accessories",
      supplier: "CJ Dropshipping",
      supplier_url: "https://cjdropshipping.com",
      product_url: "https://amazon.com",
      buy_price: 6,
      selling_price: 48,
      profit: 42,
      sales: 7600,
      ai_score: 94,
      trend_score: 92,
    },
  
    {
      name: "LED Backpack",
      image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800",
      platform: "TikTok Shop",
      category: "Fashion",
      supplier: "Zendrop",
      supplier_url: "https://zendrop.com",
      product_url: "https://tiktok.com",
      buy_price: 29,
      selling_price: 60,
      profit: 31,
      sales: 2200,
      ai_score: 91,
      trend_score: 90,
    },
  ];