-- TrendPilot AI production schema additions
-- Apply this migration in Supabase SQL editor or via Supabase CLI.

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint null,
  product_name text not null,
  platform text null,
  report jsonb not null,
  ai_score integer not null default 0,
  opportunity_score integer not null default 0,
  competition_score integer not null default 0,
  favorited boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists reports_user_created_idx
  on public.reports(user_id, created_at desc);

create index if not exists reports_user_favorited_idx
  on public.reports(user_id, favorited, created_at desc);

create index if not exists reports_product_name_idx
  on public.reports using gin (to_tsvector('english', product_name));

alter table public.reports enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'reports'
      and policyname = 'reports_select_own'
  ) then
    create policy reports_select_own
      on public.reports
      for select
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'reports'
      and policyname = 'reports_insert_own'
  ) then
    create policy reports_insert_own
      on public.reports
      for insert
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'reports'
      and policyname = 'reports_update_own'
  ) then
    create policy reports_update_own
      on public.reports
      for update
      using (auth.uid() = user_id)
      with check (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'reports'
      and policyname = 'reports_delete_own'
  ) then
    create policy reports_delete_own
      on public.reports
      for delete
      using (auth.uid() = user_id);
  end if;
end $$;
