"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { AnimatePresence, motion } from "framer-motion";
import {
  ArrowRight,
  BarChart3,
  Brain,
  Check,
  ChevronDown,
  CircleDollarSign,
  Compass,
  Gem,
  LineChart,
  Play,
  Rocket,
  Search,
  ShieldCheck,
  Sparkles,
  Star,
  TrendingUp,
  Users,
  WandSparkles,
} from "lucide-react";
import Navbar from "../Navbar";
import Footer from "../Footer";
import DashboardPreview from "./DashboardPreview";

type Feature = {
  title: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  preview: string;
};

type WorkflowStep = {
  title: string;
  description: string;
  icon: React.ComponentType<{ className?: string }>;
  detail: string;
};

type Testimonial = {
  name: string;
  role: string;
  platform: string;
  quote: string;
  avatar: string;
};

type Stat = {
  label: string;
  value: number;
  suffix: string;
  icon: React.ComponentType<{ className?: string }>;
  delta: string;
};

type Faq = {
  question: string;
  answer: string;
};

const features: Feature[] = [
  {
    title: "AI Product Analyzer",
    description:
      "Find high-potential products with confidence scoring across demand, margin, and risk.",
    icon: Search,
    preview: "Live demand and competition matrix",
  },
  {
    title: "Trend Forecast Engine",
    description:
      "Project market movement over the next 30, 60, and 90 days before spending ad budget.",
    icon: TrendingUp,
    preview: "Forecast line with momentum signals",
  },
  {
    title: "Marketing Generator",
    description:
      "Generate launch hooks, ad scripts, and content angles tailored to platform behavior.",
    icon: WandSparkles,
    preview: "Channel-ready copy templates",
  },
  {
    title: "Competitor Intelligence",
    description:
      "Track pricing pressure and creative saturation to avoid crowded product categories.",
    icon: ShieldCheck,
    preview: "Competitive pressure snapshots",
  },
  {
    title: "Revenue Modeling",
    description:
      "Simulate profitability scenarios with margin sensitivity and supplier cost assumptions.",
    icon: CircleDollarSign,
    preview: "Profit sensitivity overlays",
  },
  {
    title: "Portfolio Command Center",
    description:
      "Manage product opportunities in one operating layer with AI-driven prioritization.",
    icon: Compass,
    preview: "Opportunity ranking queue",
  },
];

const workflow: WorkflowStep[] = [
  {
    title: "Search Product Space",
    description:
      "Start with a keyword, category, or product URL. TrendPilot instantly maps demand signals.",
    icon: Search,
    detail: "Demand velocity, market depth, and supplier quality",
  },
  {
    title: "Analyze with AI",
    description:
      "AI scores each opportunity across trend strength, competition, and expected profitability.",
    icon: Brain,
    detail: "Confidence score, risk flags, and recommendation tags",
  },
  {
    title: "Launch with Precision",
    description:
      "Deploy winning products with forecast-backed decisions and marketing strategy generated by AI.",
    icon: Rocket,
    detail: "Forecast plan, messaging kit, and execution checklist",
  },
];

const stats: Stat[] = [
  {
    label: "Products Analyzed",
    value: 1200000,
    suffix: "+",
    icon: Gem,
    delta: "+28.4%",
  },
  {
    label: "Average AI Accuracy",
    value: 97,
    suffix: "%",
    icon: Brain,
    delta: "+5.1%",
  },
  {
    label: "Revenue Modeled",
    value: 42,
    suffix: "M",
    icon: LineChart,
    delta: "+19.6%",
  },
  {
    label: "Active Teams",
    value: 9300,
    suffix: "+",
    icon: Users,
    delta: "+12.3%",
  },
];

const testimonials: Testimonial[] = [
  {
    name: "Maya Chen",
    role: "DTC Founder",
    platform: "Shopify",
    quote:
      "TrendPilot changed our launch quality completely. We no longer guess products. We run a disciplined AI workflow.",
    avatar: "MC",
  },
  {
    name: "Jordan Smith",
    role: "Marketplace Operator",
    platform: "Amazon",
    quote:
      "The forecasting and competitor modules saved us months of trial and error. It feels like having an in-house strategy desk.",
    avatar: "JS",
  },
  {
    name: "Leila Omar",
    role: "Growth Lead",
    platform: "TikTok Shop",
    quote:
      "The marketing generator and product scores gave us immediate clarity on what to test first and what to ignore.",
    avatar: "LO",
  },
];

const faqs: Faq[] = [
  {
    question: "How is the AI score calculated?",
    answer:
      "TrendPilot combines demand velocity, competition saturation, expected margin, and supplier reliability into one weighted signal.",
  },
  {
    question: "Can I use this with Shopify workflows?",
    answer:
      "Yes. Teams use TrendPilot before sourcing and creative planning, then execute directly through their Shopify stack.",
  },
  {
    question: "Does the free plan include real AI analysis?",
    answer:
      "Yes. The FREE plan gives 5 analyses per day with core AI scoring so users can evaluate product fit before upgrading.",
  },
  {
    question: "Is TrendPilot suitable for teams?",
    answer:
      "Yes. PREMIUM includes team access, API, bulk analysis, and advanced forecasting built for collaborative decision workflows.",
  },
];

function CountUp({ value, suffix }: { value: number; suffix: string }) {
  const [count, setCount] = useState(0);

  useEffect(() => {
    let frame = 0;
    const duration = 1400;
    const start = performance.now();

    const step = (timestamp: number) => {
      const elapsed = timestamp - start;
      const progress = Math.min(elapsed / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      setCount(Math.floor(value * eased));

      if (progress < 1) {
        frame = requestAnimationFrame(step);
      }
    };

    frame = requestAnimationFrame(step);

    return () => {
      cancelAnimationFrame(frame);
    };
  }, [value]);

  return (
    <span>
      {count.toLocaleString()}
      {suffix}
    </span>
  );
}

function SectionHeader({
  eyebrow,
  title,
  description,
}: {
  eyebrow: string;
  title: string;
  description: string;
}) {
  return (
    <div className="mx-auto mb-12 max-w-3xl text-center lg:mb-16">
      <p className="text-xs font-semibold uppercase tracking-[0.26em] text-violet-300">{eyebrow}</p>
      <h2 className="mt-4 text-4xl font-extrabold leading-tight text-white sm:text-5xl lg:text-6xl">{title}</h2>
      <p className="mt-5 text-base leading-relaxed text-slate-300 sm:text-lg">{description}</p>
    </div>
  );
}

function FeatureCard({ feature, index }: { feature: Feature; index: number }) {
  const Icon = feature.icon;
  const bars = [52, 74, 61, 84, 68];

  return (
    <motion.div
      className="group relative overflow-hidden rounded-3xl border border-white/10 bg-[rgba(17,24,39,0.62)] p-6 shadow-[0_24px_70px_-36px_rgba(124,58,237,0.82)] backdrop-blur-xl"
      whileHover={{ y: -8, scale: 1.01 }}
      transition={{ type: "spring", stiffness: 260, damping: 24 }}
    >
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(168,85,247,0.22),transparent_40%)] opacity-80" />
      <div className="relative z-10 flex h-full flex-col">
        <div className="inline-flex h-14 w-14 items-center justify-center rounded-2xl border border-white/20 bg-gradient-to-br from-violet-500 to-cyan-400 text-white shadow-lg shadow-violet-900/45">
          <Icon className="h-6 w-6" />
        </div>

        <h3 className="mt-5 text-2xl font-bold tracking-tight text-white">{feature.title}</h3>
        <p className="mt-3 text-sm leading-relaxed text-slate-300">{feature.description}</p>

        <div className="mt-5 rounded-2xl border border-white/10 bg-slate-950/45 p-4">
          <p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-slate-400">Preview</p>
          <p className="mt-2 text-sm text-slate-200">{feature.preview}</p>

          <div className="mt-4 flex h-9 items-end gap-1.5">
            {bars.map((height, barIndex) => (
              <motion.div
                key={`${feature.title}-${barIndex}`}
                className="w-full rounded-t-sm bg-gradient-to-t from-violet-600 to-cyan-300"
                style={{ height: `${height - index * 2}%` }}
                initial={{ scaleY: 0 }}
                whileInView={{ scaleY: 1 }}
                viewport={{ once: true, amount: 0.5 }}
                transition={{ delay: barIndex * 0.08, duration: 0.45 }}
              />
            ))}
          </div>
        </div>
      </div>
    </motion.div>
  );
}

function PricingCard({
  name,
  price,
  period,
  features,
  highlighted,
  href,
}: {
  name: string;
  price: string;
  period: string;
  features: string[];
  highlighted?: boolean;
  href: string;
}) {
  return (
    <motion.div
      className={`relative rounded-3xl border p-8 backdrop-blur-xl ${
        highlighted
          ? "scale-[1.02] border-violet-300/40 bg-[radial-gradient(circle_at_top_right,rgba(124,58,237,0.35),transparent_44%),rgba(17,24,39,0.78)] shadow-[0_34px_100px_-36px_rgba(124,58,237,0.98)]"
          : "border-white/10 bg-[rgba(17,24,39,0.62)] shadow-[0_26px_90px_-40px_rgba(15,23,42,0.95)]"
      }`}
      whileHover={{ y: -10 }}
      transition={{ type: "spring", stiffness: 280, damping: 26 }}
    >
      {highlighted ? (
        <div className="absolute left-8 top-6 rounded-full border border-violet-300/50 bg-violet-500/25 px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.16em] text-violet-100">
          Most Popular
        </div>
      ) : null}

      <div className={`relative ${highlighted ? "pt-8" : ""}`}>
        <p className="text-xl font-bold uppercase tracking-[0.08em] text-white">{name}</p>
        <div className="mt-5 flex items-end gap-2">
          <span className="text-5xl font-black tracking-tight text-white">{price}</span>
          <span className="pb-2 text-sm text-slate-400">{period}</span>
        </div>

        <ul className="mt-7 space-y-3">
          {features.map((item) => (
            <li key={item} className="flex items-start gap-2 text-sm text-slate-200">
              <Check className="mt-0.5 h-4 w-4 shrink-0 text-cyan-300" />
              {item}
            </li>
          ))}
        </ul>

        <Link
          href={href}
          className={`mt-8 inline-flex w-full items-center justify-center gap-2 rounded-full px-5 py-3 text-sm font-semibold transition-all duration-300 hover:-translate-y-0.5 ${
            highlighted
              ? "border border-violet-300/40 bg-gradient-to-r from-violet-600 to-fuchsia-500 text-white shadow-[0_18px_44px_-18px_rgba(124,58,237,0.95)]"
              : "border border-white/20 bg-white/5 text-slate-100 hover:bg-white/10"
          }`}
        >
          {highlighted ? "Upgrade to PRO" : "Get Started"}
          <ArrowRight className="h-4 w-4" />
        </Link>
      </div>
    </motion.div>
  );
}

function FaqItem({
  item,
  open,
  onToggle,
}: {
  item: Faq;
  open: boolean;
  onToggle: () => void;
}) {
  return (
    <div className="overflow-hidden rounded-2xl border border-white/10 bg-[rgba(17,24,39,0.58)] backdrop-blur-xl">
      <button
        type="button"
        onClick={onToggle}
        className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left transition hover:bg-white/5"
      >
        <span className="font-semibold text-white">{item.question}</span>
        <ChevronDown className={`h-5 w-5 text-violet-300 transition-transform ${open ? "rotate-180" : ""}`} />
      </button>

      <AnimatePresence initial={false}>
        {open ? (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25 }}
          >
            <p className="border-t border-white/10 px-5 pb-5 pt-4 text-sm leading-relaxed text-slate-300">{item.answer}</p>
          </motion.div>
        ) : null}
      </AnimatePresence>
    </div>
  );
}

export default function LandingPage() {
  const [openFaq, setOpenFaq] = useState(0);

  return (
    <div className="relative overflow-hidden bg-[#050816] text-white">
      <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_12%_8%,rgba(124,58,237,0.28),transparent_34%),radial-gradient(circle_at_88%_12%,rgba(56,189,248,0.18),transparent_32%),linear-gradient(180deg,#050816_0%,#050816_100%)]" />
      <div className="pointer-events-none absolute inset-0 bg-[linear-gradient(rgba(148,163,184,0.08)_1px,transparent_1px),linear-gradient(90deg,rgba(148,163,184,0.08)_1px,transparent_1px)] bg-[size:56px_56px] opacity-30 [mask-image:radial-gradient(circle_at_center,black,transparent_84%)]" />

      <motion.div
        className="pointer-events-none absolute -left-24 top-24 h-80 w-80 rounded-full bg-violet-600/25 blur-3xl"
        animate={{ y: [0, 20, 0], x: [0, 12, 0], opacity: [0.5, 0.85, 0.5] }}
        transition={{ duration: 14, repeat: Number.POSITIVE_INFINITY, ease: "easeInOut" }}
      />
      <motion.div
        className="pointer-events-none absolute -right-28 top-40 h-96 w-96 rounded-full bg-cyan-500/20 blur-3xl"
        animate={{ y: [0, -16, 0], x: [0, -10, 0], opacity: [0.45, 0.75, 0.45] }}
        transition={{ duration: 16, repeat: Number.POSITIVE_INFINITY, ease: "easeInOut" }}
      />

      <Navbar />

      <main className="relative z-10">
        <section className="px-4 pb-20 pt-36 sm:px-6 lg:px-8">
          <div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.02fr_0.98fr]">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
              className="space-y-8"
            >
              <div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-[rgba(15,23,42,0.72)] px-4 py-2 text-xs font-semibold uppercase tracking-[0.2em] text-violet-200 backdrop-blur-xl">
                <Sparkles className="h-4 w-4" />
                Enterprise AI Product Intelligence
              </div>

              <h1 className="text-5xl font-extrabold leading-[1.02] tracking-tight sm:text-6xl lg:text-7xl">
                <span className="bg-gradient-to-r from-white via-violet-200 to-cyan-200 bg-clip-text text-transparent">
                  Find Winning Products
                </span>
                <br />
                <span className="text-white">Before They Break Out.</span>
              </h1>

              <p className="max-w-2xl text-lg leading-relaxed text-slate-300 sm:text-xl">
                TrendPilot gives modern ecommerce teams a premium AI workspace for product discovery, trend validation, margin modeling, and launch execution.
              </p>

              <div className="flex flex-col gap-3 sm:flex-row">
                <Link
                  href="/register"
                  className="inline-flex items-center justify-center gap-2 rounded-full border border-violet-300/40 bg-gradient-to-r from-violet-600 to-fuchsia-500 px-7 py-3.5 text-sm font-semibold text-white shadow-[0_20px_60px_-24px_rgba(124,58,237,0.95)] transition-all duration-300 hover:-translate-y-0.5"
                >
                  Start Free Trial
                  <ArrowRight className="h-4 w-4" />
                </Link>

                <a
                  href="#how-it-works"
                  className="inline-flex items-center justify-center gap-2 rounded-full border border-white/20 bg-white/5 px-7 py-3.5 text-sm font-semibold text-slate-100 transition-all duration-300 hover:-translate-y-0.5 hover:bg-white/10"
                >
                  Watch Workflow
                  <Play className="h-4 w-4" />
                </a>
              </div>

              <div className="flex flex-wrap items-center gap-4 text-sm text-slate-300">
                <div className="flex items-center gap-1 text-amber-400">
                  {Array.from({ length: 5 }).map((_, idx) => (
                    <Star key={idx} className="h-4 w-4 fill-current" />
                  ))}
                </div>
                Trusted by operators across Shopify, Amazon, and TikTok Shop.
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, scale: 0.95, rotateX: 8, rotateY: -4, y: 20 }}
              animate={{ opacity: 1, scale: 1, rotateX: 2.5, rotateY: -2.5, y: 0 }}
              transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
              whileHover={{ rotateX: 1.2, rotateY: -1.2 }}
              className="relative [transform-style:preserve-3d]"
              style={{ transformPerspective: 1700 }}
            >
              <div className="absolute -inset-7 rounded-[2rem] bg-gradient-to-r from-violet-600/25 to-cyan-500/18 blur-3xl" />
              <div className="relative overflow-visible rounded-[2rem] border border-white/10 bg-[rgba(15,23,42,0.72)] p-4 shadow-[0_44px_120px_-44px_rgba(124,58,237,0.95)] backdrop-blur-xl">
                <div className="mb-4 flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs text-slate-300">
                  <span className="h-2.5 w-2.5 rounded-full bg-rose-400" />
                  <span className="h-2.5 w-2.5 rounded-full bg-amber-400" />
                  <span className="h-2.5 w-2.5 rounded-full bg-emerald-400" />
                  <span className="ml-2 rounded-full border border-white/10 bg-slate-900/70 px-3 py-1">trendpilot.ai / intelligence / product-opportunity</span>
                </div>

                <DashboardPreview />

                <motion.div
                  className="pointer-events-none absolute -right-6 -top-5 rounded-2xl border border-white/15 bg-slate-900/78 px-4 py-3 text-white backdrop-blur-xl"
                  animate={{ y: [0, -6, 0] }}
                  transition={{ duration: 4.4, repeat: Number.POSITIVE_INFINITY, ease: "easeInOut" }}
                >
                  <p className="text-[10px] uppercase tracking-[0.16em] text-slate-400">AI Score</p>
                  <p className="text-xl font-black text-emerald-300">96 / 100</p>
                </motion.div>

                <motion.div
                  className="pointer-events-none absolute -left-8 top-16 rounded-xl border border-white/15 bg-slate-900/75 px-3 py-2 text-xs text-slate-100 backdrop-blur-xl"
                  animate={{ x: [0, 4, 0], y: [0, -4, 0] }}
                  transition={{ duration: 5, repeat: Number.POSITIVE_INFINITY, ease: "easeInOut" }}
                >
                  <p className="text-[10px] uppercase tracking-[0.16em] text-slate-400">Revenue</p>
                  <p className="font-bold text-cyan-300">$42.8K</p>
                </motion.div>

                <motion.div
                  className="pointer-events-none absolute -bottom-5 left-12 rounded-xl border border-white/15 bg-slate-900/75 px-3 py-2 text-xs text-slate-100 backdrop-blur-xl"
                  animate={{ y: [0, 5, 0] }}
                  transition={{ duration: 4.8, repeat: Number.POSITIVE_INFINITY, ease: "easeInOut" }}
                >
                  <p className="text-[10px] uppercase tracking-[0.16em] text-slate-400">Profit</p>
                  <p className="font-bold text-emerald-300">$21.10 / unit</p>
                </motion.div>
              </div>
            </motion.div>
          </div>
        </section>

        <section className="px-4 py-20 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-7xl">
            <SectionHeader
              eyebrow="Statistics"
              title="Operational Signal at a Glance"
              description="High-fidelity analytics cards with animated counters and live movement cues for executive-level clarity."
            />

            <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">
              {stats.map((item, idx) => {
                const Icon = item.icon;
                return (
                  <motion.div
                    key={item.label}
                    className="group relative overflow-hidden rounded-3xl border border-white/10 bg-[rgba(17,24,39,0.6)] p-6 shadow-[0_22px_70px_-38px_rgba(124,58,237,0.84)] backdrop-blur-xl"
                    initial={{ opacity: 0, y: 18 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true, amount: 0.3 }}
                    transition={{ delay: idx * 0.08, duration: 0.5 }}
                    whileHover={{ y: -8, scale: 1.01 }}
                  >
                    <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(124,58,237,0.24),transparent_40%)] opacity-80" />

                    <div className="relative z-10">
                      <div className="flex items-start justify-between">
                        <div className="inline-flex h-12 w-12 items-center justify-center rounded-2xl border border-white/20 bg-gradient-to-br from-violet-500 to-cyan-400 text-white">
                          <Icon className="h-5 w-5" />
                        </div>
                        <span className="rounded-full border border-emerald-300/35 bg-emerald-500/12 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.14em] text-emerald-300">
                          {item.delta}
                        </span>
                      </div>

                      <p className="mt-5 text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">{item.label}</p>
                      <p className="mt-2 text-4xl font-black tracking-tight text-white">
                        <CountUp value={item.value} suffix={item.suffix} />
                      </p>
                    </div>
                  </motion.div>
                );
              })}
            </div>
          </div>
        </section>

        <section id="how-it-works" className="px-4 py-20 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-7xl">
            <SectionHeader
              eyebrow="How It Works"
              title="A Connected Launch Workflow"
              description="A premium timeline from product search to AI analysis to launch execution, with clear directional flow."
            />

            <div className="grid gap-4 lg:grid-cols-3 lg:gap-6">
              {workflow.map((step, index) => {
                const Icon = step.icon;
                return (
                  <motion.div
                    key={step.title}
                    className="relative rounded-3xl border border-white/10 bg-[rgba(17,24,39,0.6)] p-6 backdrop-blur-xl"
                    initial={{ opacity: 0, y: 16 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true, amount: 0.35 }}
                    transition={{ delay: index * 0.1, duration: 0.45 }}
                    whileHover={{ y: -6 }}
                  >
                    {index < workflow.length - 1 ? (
                      <div className="pointer-events-none absolute -right-5 top-1/2 hidden h-8 w-8 -translate-y-1/2 items-center justify-center rounded-full border border-white/15 bg-slate-900/80 text-violet-300 lg:flex">
                        <ArrowRight className="h-4 w-4" />
                      </div>
                    ) : null}

                    <div className="inline-flex h-12 w-12 items-center justify-center rounded-2xl border border-white/20 bg-gradient-to-br from-violet-500 to-cyan-400 text-white">
                      <Icon className="h-5 w-5" />
                    </div>

                    <p className="mt-4 text-[11px] font-semibold uppercase tracking-[0.16em] text-violet-300">Step {index + 1}</p>
                    <h3 className="mt-2 text-2xl font-bold tracking-tight text-white">{step.title}</h3>
                    <p className="mt-3 text-sm leading-relaxed text-slate-300">{step.description}</p>

                    <div className="mt-5 rounded-2xl border border-white/10 bg-slate-950/45 p-4">
                      <p className="text-xs text-cyan-200">{step.detail}</p>
                      <div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/10">
                        <motion.div
                          className="h-full rounded-full bg-gradient-to-r from-violet-400 to-cyan-300"
                          initial={{ width: 0 }}
                          whileInView={{ width: `${70 + index * 10}%` }}
                          viewport={{ once: true }}
                          transition={{ duration: 0.7, delay: index * 0.12 }}
                        />
                      </div>
                    </div>
                  </motion.div>
                );
              })}
            </div>
          </div>
        </section>

        <section id="features" className="px-4 py-20 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-7xl">
            <SectionHeader
              eyebrow="Features"
              title="Purpose-Built for Modern Product Teams"
              description="Each module blends intelligence, visual hierarchy, and execution speed in one premium command surface."
            />

            <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">
              {features.map((feature, index) => (
                <FeatureCard key={feature.title} feature={feature} index={index} />
              ))}
            </div>
          </div>
        </section>

        <section id="pricing" className="px-4 py-20 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-7xl">
            <SectionHeader
              eyebrow="Pricing"
              title="Choose the Right Growth Tier"
              description="Simple transparent plans for solo operators, growth-focused teams, and advanced organizations."
            />

            <div className="grid gap-6 lg:grid-cols-3 lg:items-stretch">
              <PricingCard
                name="FREE"
                price="$0"
                period="/month"
                href="/register"
                features={[
                  "5 product analyses/day",
                  "Basic AI",
                  "Limited history",
                  "Community support",
                ]}
              />

              <PricingCard
                name="PRO"
                price="$49"
                period="/month"
                href="/pricing"
                highlighted
                features={[
                  "Unlimited product searches",
                  "AI Reports",
                  "Competitor Analysis",
                  "Trend Prediction",
                  "Marketing Generator",
                  "Export",
                  "Priority Support",
                ]}
              />

              <PricingCard
                name="PREMIUM"
                price="$99"
                period="/month"
                href="/pricing"
                features={[
                  "Everything in Pro",
                  "Team members",
                  "API",
                  "Bulk analysis",
                  "Advanced forecasting",
                  "White-label reports",
                  "Premium support",
                ]}
              />
            </div>
          </div>
        </section>

        <section id="testimonials" className="px-4 py-20 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-7xl">
            <SectionHeader
              eyebrow="Testimonials"
              title="Trusted by High-Performance Teams"
              description="Premium customer proof from operators who rely on AI-assisted decisions to launch faster and scale cleaner."
            />

            <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
              {testimonials.map((item, idx) => (
                <motion.div
                  key={item.name}
                  className="relative overflow-hidden rounded-3xl border border-transparent bg-[linear-gradient(#111827,#111827)_padding-box,linear-gradient(135deg,rgba(168,85,247,0.8),rgba(56,189,248,0.7))_border-box] p-6"
                  initial={{ opacity: 0, y: 16 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true, amount: 0.35 }}
                  transition={{ delay: idx * 0.08, duration: 0.45 }}
                  whileHover={{ y: -8 }}
                >
                  <div className="mb-4 flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <div className="flex h-11 w-11 items-center justify-center rounded-full border border-violet-300/40 bg-gradient-to-br from-violet-600 to-cyan-400 text-sm font-bold text-white">
                        {item.avatar}
                      </div>
                      <div>
                        <p className="font-semibold text-white">{item.name}</p>
                        <p className="text-xs text-slate-400">{item.role}</p>
                      </div>
                    </div>
                    <span className="rounded-full border border-white/15 bg-white/5 px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.14em] text-cyan-200">
                      {item.platform}
                    </span>
                  </div>

                  <div className="mb-3 flex gap-1 text-amber-400">
                    {Array.from({ length: 5 }).map((_, starIndex) => (
                      <Star key={`${item.name}-${starIndex}`} className="h-4 w-4 fill-current" />
                    ))}
                  </div>

                  <p className="text-sm leading-relaxed text-slate-200">{item.quote}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        <section id="faq" className="px-4 pb-20 pt-8 sm:px-6 lg:px-8">
          <div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1.1fr_0.9fr]">
            <div className="rounded-3xl border border-white/10 bg-[rgba(17,24,39,0.62)] p-8 backdrop-blur-xl">
              <p className="text-xs font-semibold uppercase tracking-[0.24em] text-violet-300">Launch with confidence</p>
              <h3 className="mt-4 text-4xl font-extrabold tracking-tight text-white sm:text-5xl">Build your next winning product portfolio.</h3>
              <p className="mt-4 text-base leading-relaxed text-slate-300">
                TrendPilot combines AI market intelligence, predictive analytics, and execution workflows in one premium interface.
              </p>

              <div className="mt-8 flex flex-col gap-3 sm:flex-row">
                <Link
                  href="/register"
                  className="inline-flex items-center justify-center gap-2 rounded-full border border-violet-300/40 bg-gradient-to-r from-violet-600 to-fuchsia-500 px-6 py-3 text-sm font-semibold text-white shadow-[0_18px_48px_-20px_rgba(124,58,237,0.92)]"
                >
                  Start Free
                  <ArrowRight className="h-4 w-4" />
                </Link>

                <Link
                  href="/pricing"
                  className="inline-flex items-center justify-center gap-2 rounded-full border border-white/20 bg-white/5 px-6 py-3 text-sm font-semibold text-white transition hover:bg-white/10"
                >
                  View Plans
                  <BarChart3 className="h-4 w-4" />
                </Link>
              </div>
            </div>

            <div className="space-y-3">
              {faqs.map((item, index) => (
                <FaqItem
                  key={item.question}
                  item={item}
                  open={openFaq === index}
                  onToggle={() => setOpenFaq(openFaq === index ? -1 : index)}
                />
              ))}
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
